### PR TITLE
GHC 8.8.2

### PR DESCRIPTION
**Pull request by zimbatm**
another attempt at #32

### CODE REVIEW

**Comment by domenkozar** [comment]
```
2020-03-20T20:36:42.2889123Z building '/nix/store/6q77v2fiv405xxp4sra4cxwnm6x8yx7f-ghc882-bytestring-sdist.tar.gz.drv'...
2020-03-20T20:36:42.3851806Z Wrote tarball sdist to /build/tmp.MyXGQkLMkm/bytestring-0.10.10.0.tar.gz
2020-03-20T20:36:42.4366286Z building '/nix/store/gdjilks1s9nsijngdy2l7jgp1axy5rca-package-nix.drv'...
2020-03-20T20:36:42.4898657Z unpacking sources
2020-03-20T20:36:42.4905564Z unpacking source archive /nix/store/yadrwlbdq5d3r5cbxm8c91adklb7971c-ghc882-bytestring-sdist.tar.gz
2020-03-20T20:36:42.4992375Z source root is bytestring-0.10.10.0
2020-03-20T20:36:42.5101003Z setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file bytestring-0.10.10.0/tests/TestFramework.hs
2020-03-20T20:36:42.5124093Z building
2020-03-20T20:36:42.6790683Z building '/nix/store/6qkh97qb2s8ax4ydnmilka68k5ghl1vj-ghc882-ghc-sdist.tar.gz.drv'...
2020-03-20T20:36:44.4379897Z Wrote tarball sdist to /build/tmp.6OFaOCbpLo/ghc-8.8.2.tar.gz
2020-03-20T20:36:44.5867578Z building '/nix/store/zq4zgs9ggm93ha7h71jxf0q9axr5d74r-package-nix.drv'...
2020-03-20T20:36:44.6382590Z unpacking sources
2020-03-20T20:36:44.6390631Z unpacking source archive /nix/store/h604mnq3x14837phh16hkg6g2wgirpmq-ghc882-ghc-sdist.tar.gz
2020-03-20T20:36:44.7693733Z source root is ghc-8.8.2
2020-03-20T20:36:44.7837830Z setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file ghc-8.8.2/utils/Util.hs
2020-03-20T20:36:44.7860197Z building
2020-03-20T20:36:44.8545388Z error: The Haskell package set does not contain the package: text (build dependency).
2020-03-20T20:36:44.8545531Z 
2020-03-20T20:36:44.8545786Z If you are using Stackage, make sure that you are using a snapshot that contains the package. Otherwise you may need to update the Hackage snapshot you are using, usually by updating haskell.nix.
2020-03-20T20:36:44.8545951Z 
```

**Comment by zimbatm** [comment]
hmm yeah, this is reproducible

**Comment by zimbatm** [comment]
any ideas?

**Comment by domenkozar** [comment]
Need to play with relocatable packages and update to 8.8.3 :)

**Comment by zimbatm** [comment]
I tried with 8.8.3 and it gives the same result. Do you have some pointers about the relocatable packages so I can look into it?

**Comment by domenkozar** [comment]
https://github.com/input-output-hk/haskell.nix/issues/440

**Comment by dhess** [comment]
Probably the same as https://github.com/input-output-hk/haskell.nix/issues/481

**Comment by domenkozar** [comment]
I gave this a go, seems like we're now waiting for angerman to update stackage.nix then we can give it another try.

**Comment by domenkozar** [comment]
#32 now builds on linux, just need to sort out mac :)

**Pull request closed without merging**
