### PR TITLE
Update ghcide to 0.0.4

### PR DESCRIPTION
**Pull request by jacg**
Not entirely sure how to verify locally whether these changes are coherent.

Please advise.

### CODE REVIEW

**Comment by roberth** [comment]
/bors try

@jacg Is this from the `update` script?

**Comment by roberth** [comment]
bors try

**Comment by jacg** [comment]
@roberth The update script fails with
````
error: attempt to call something which is not a function but a set, at /home/jacek/src/ghcide-nix/nix/default.nix:5:20
./update: line 15: /bin/stack-to-nix: No such file or directory
````

**Comment by roberth** [comment]
`haskell.nix` has changed interface.
I will try to upgrade it and ghcide soon.

**Comment by rossabaker** [comment]
A couple of us were looking at upgrading last week and got [this branch compiling](https://github.com/EarnestResearch/ghcide-nix/tree/this_compiles).  It addresses the error above, but fails on my haskell.nix project with:

```
Step 4/6, Cradle 1/1: Loading GHC Session
ghcide: ghcide: this operation requires -fexternal-interpreter
```

**Comment by domenkozar** [comment]
That one is peculiar.

**Comment by roberth** [comment]
My setup uses a custom `hie.yaml` so I could just add it, which makes it work.
I'd expect ghcide to hardcode it if necessary. https://github.com/digital-asset/ghcide/issues/206

**Comment by domenkozar** [comment]
done in https://github.com/hercules-ci/ghcide-nix/pull/20

**Pull request closed without merging**
