### PR TITLE
Add vscode extension

### PR DESCRIPTION
**Pull request by roberth**
Will do some upstreaming later.

- [x] test (refactored code)
- [x] add to README

### CODE REVIEW

**Comment by domenkozar** [comment]
Ugh, this is going to be useless next week when it's added to VSCode market.

**Comment by roberth** [comment]
Not if you want to hack on it.

**Comment by roberth** [comment]
Not requiring a release is a feature.

**Comment by domenkozar** [comment]
There's no need to hack or release, the whole integration is 44 lines of code: https://github.com/digital-asset/ghcide/blob/master/extension/src/extension.ts

**Comment by roberth** [comment]
Famous last words ;).
Anyway, this fixes my setup :man_shrugging:

**Comment by domenkozar** [comment]
The extension is now on the marketplace under `ghcide`, so it can be just packaged to nixpkgs.

The instructions on how to install the extension should be upstream.

This goal of this repo to install ghcide smoothly, not to be able to develop it.

**Pull request closed without merging**
