### PR TITLE
Update haskell.nix, simplify a lot

### PR DESCRIPTION
**Pull request by roberth**
- [ ] test

### CODE REVIEW

**Comment by domenkozar** [comment]
`./update` script was there to support days when ghcide has git dependencies, which happens all the time due to haskell-lsp and hie-bios bumps.

**Comment by roberth** [comment]
Git versions are supported but a bit cumbersome with the `cache` parameter. Here's an [example.](https://github.com/input-output-hk/haskell.nix/blob/b8af9902c289c0403c43c5e0ac7ee1e00f6dbbda/examples/cardano-wallet-args.nix#L23)
After https://github.com/input-output-hk/haskell.nix/issues/309 is implemented, it will be automatic.

**Comment by domenkozar** [comment]
Don't think manually crafting those is an improvement of automation, I'd rather have to run one command.

**Comment by roberth** [comment]
Blocked on https://github.com/input-output-hk/haskell.nix/issues/309

**Comment by roberth** [comment]
This will support diverging stack.yamls

**Pull request merged**
